nacos:
  server_configs:
    - ip_addr: "82.157.212.7"
      port: 8848
      grpc_port: 9848
  client_config:
    namespace_id: "18b01bb8-ac70-4527-89d0-01079f30ca09"
    timeout_ms: 5000
    not_load_cache_at_start: true
    log_dir: "/tmp/nacos/log"
    cache_dir: "/tmp/nacos/cache"
    log_level: "debug"
  namespace_id: "18b01bb8-ac70-4527-89d0-01079f30ca09"
  group: "DEFAULT_GROUP"
  data_id: "chat-models"
