# Nacos 配置
nacos:
  server_configs:
    - ip_addr: "127.0.0.1"
      port: 8848
  client_config:
    namespace_id: "public"
    timeout_ms: 5000
  namespace_id: "public"
  group: "DEFAULT_GROUP"
  data_id: "chat-models"

# 服务器配置
server:
  port: "8080"
  host: "0.0.0.0"
